name: Tests
on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
      branches:
        - main
        - 'release-*'
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true 

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install packages
        run: yarn install:ci

      - name: Run i18n linters
        run: yarn lint-l10n

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install packages
        run: yarn install:ci

      - name: Run linters
        run: yarn lint

