name: Tests
on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
      branches:
        - main
        - 'release-*'
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true 

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install packages
        run: yarn install:ci

      - name: Run i18n linters
        run: yarn lint-l10n

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install packages
        run: yarn install:ci

      - name: Run linters
        run: yarn lint

  hosted-master:
    runs-on: ubuntu-latest
    needs: [lint, i18n]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: ./scripts/build-hosted
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY }}
          access-key-secret: ${{ secrets.ALIYUN_SECRET_KEY }}
      - run: ossutil cp -rf dist/ oss://1block/dashboard/
  
  embedded-master:
    runs-on: ubuntu-latest
    needs: [lint, i18n]
    env:
      TARBALL: latest.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Embedded
        run: ./scripts/build-embedded

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY }}
          access-key-secret: ${{ secrets.ALIYUN_SECRET_KEY }}
      - run: ossutil cp -rf dist/$TARBALL oss://1block/dashboard/
